### ISSUE TITLE
Steven Black list is already included in default NextDNS list

### ISSUE THREAD

**Issue by beerisgood** [scafroglia93/nextdns-setting#2]
See https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json & https://github.com/nextdns/metadata/blob/master/privacy/blocklists/nextdns-recommended.json

No need for enable it twice :)

**Comment by scafroglia93** [comment]
I know but since they do not create performance problems I prefer to take advantage of the redundancy since some of them are not updated in real time or have more updated entries
