### ISSUE TITLE
oisd already have StevenBlack and Adguard rules inlcluded

### ISSUE THREAD

**Issue by FadeMind** [scafroglia93/nextdns-setting#3]
@scafroglia93 Hi. Massive `oisd` already have Steven Black and Adguard filter without false positives. 
See more at: https://oisd.nl/?p=inc

![20210309-1615320066-001](https://user-images.githubusercontent.com/9846948/110530351-a0181e00-811a-11eb-85ec-0059f3a1ea01.png)
![20210309-1615320050-001](https://user-images.githubusercontent.com/9846948/110530354-a0b0b480-811a-11eb-819b-78c7dfdeb78d.png)

**Comment by scafroglia93** [comment]
The observation is correct but I am telling you that oisd has whitelisted the domains connected to iubenda and personally gives me a lot of trouble with the "cookie policy" banners

Nothing prevents you from taking a cue from my list and creating your own variant

thanks

**Comment by FadeMind** [comment]
@scafroglia93 understood 😁
